name: Generate Snake

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: "ElielElanoChavesSilva"
          outputs: |
            output/github-contribution-grid-snake.svg

      # garante que o branch output existe
      - name: Create output branch if it doesn't exist
        run: |
          git fetch origin
          if ! git ls-remote --heads origin output | grep output; then
            echo "Branch output not found. Creating..."
            git checkout -b output
            git push origin output
          else
            echo "Branch output already exists."
          fi

      - name: Commit and push snake
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate snake animation"
          branch: output
          file_pattern: output/**
